program ::= declaration* EOF

declaration ::= funDecl | procDecl | classDecl | statement

statement ::= exprStmt
                | globalStmt
                | forStmt
                | whileStmt
                | doStmt
                | ifStmt
                | switchStmt

expression ::= assignment

assignment ::= ((call ".")? IDENTIFIER "=" assignment) | logicOr
logicOr ::= logicAnd ("OR" logicAnd)*
logicAnd ::= equality ("AND" equality)*
equality ::= comparison (("==" | "!=") comparison)*
comparison ::= term (("<" | "<=" | ">" | ">=") term)*
term ::= factor (("+" | "-") factor)*
factor ::= unary (("*" | "/") unary)*
unary ::= ("NOT" | "-" | "new") unary | call
call ::= primary ("(" arguments? ")" | "." IDENTIFIER)*
primary ::= "self" | NUMBER | STRING | IDENTIFIER | "(" expression ")"
            | "super" "." IDENTIFIER
